---
- block:

    - name: install yum version lock support
      package:
        name: yum-plugin-versionlock
      when: ansible_os_family == 'RedHat'

    - name: disable yum package lock
      command: "yum versionlock delete {{ item }}"
      ignore_errors: yes
      loop: "{{ [heartbeat_package_names] | flatten }}"
      when: ansible_os_family == 'RedHat'
      tags:
        - skip_ansible_lint

    - name: disable apt package lock
      command: "apt-mark unhold {{ item }}"
      loop: "{{ [heartbeat_package_names] | flatten }}"
      when: ansible_os_family == 'Debian'

  when: heartbeat_package_hold | bool
  ignore_errors: yes

- name: install heartbeat packages
  package:
    name: "{{ heartbeat_package_names }}"
    state: "{{ heartbeat_package_state }}"

- block:

    - name: enable apt package hold
      command: "apt-mark hold {{ item }}"
      loop: "{{ [heartbeat_package_names] | flatten }}"
      when:
        - ansible_os_family == 'Debian'

    - name: enable yum package lock
      command: "yum versionlock add {{ item }}"
      loop: "{{ [heartbeat_package_names] | flatten }}"
      when:
        - ansible_os_family == 'RedHat'
      tags:
        - skip_ansible_lint

  when: heartbeat_package_hold | bool

- name: configure authkey
  template:
    src: "{{ heartbeat_authkey_file }}"
    dest: "{{ heartbeat_authkey_path }}"
    owner: root
    group: root
    mode: 0600
  notify: restart heartbeat
  when:
    - heartbeat_authkey_file is defined

- name: configure heartbeat
  template:
    src: "{{ heartbeat_conf_file }}"
    dest: "{{ heartbeat_conf_path }}"
    owner: root
    group: root
    mode: 0600
  notify: restart heartbeat
  when:
    - heartbeat_conf_file is defined

- name: configure haressources
  template:
    src: "{{ heartbeat_haressources_file }}"
    dest: "{{ heartbeat_haressources_path }}"
    owner: root
    group: root
    mode: 0600
  notify: restart heartbeat
  when:
    - heartbeat_haressources_file is defined

- name: manage heartbeat services
  service:
    name: "{{ heartbeat_service_name }}"
    state: "{{ heartbeat_service_status }}"
    enabled: "{{ heartbeat_service_enabled }}"
